### PR TITLE
update bytes crate

### PR DESCRIPTION
**Pull request by Tarnadas**

### CODE REVIEW

**Comment by stepancheg** [comment]
Note CI is not green.

I suspect bytes 0.6 is backwards-incompatible with 0.5?

**Comment by Tarnadas** [comment]
Yeah I should have tested this locally before pushing.

So there is this issue which has been fixed: https://github.com/tokio-rs/bytes/issues/328
I  am definitely not that familiar with unsafe casting, but I just pushed a change which should compile

**Comment by Tarnadas** [comment]
The only thing I could think about is to split this up into multiple features, so there would be e.g. `with-bytes05` and `with-bytes06`

**Comment by stepancheg** [comment]
That would be overkill.

**Comment by Tarnadas** [comment]
I’m wondering why you would want to have compatibility for both versions?
I don’t think this could be easily achieved

**Comment by stepancheg** [comment]
> I’m wondering why you would want to have compatibility for both versions?

Otherwise users of protobuf crate will be forced to upgrade their projects for compatibility with newer bytes.

> I don’t think this could be easily achieved

Seems so.

**Comment by stepancheg** [comment]
Pushed to master with minor changes. Thanks! Now going to merge to 2.19 (next stable) branch.

**Pull request closed without merging**
