### PR TITLE
Increase limit from u32 to a u64

### PR DESCRIPTION
**Pull request by luke-clifton**
I find that I sometimes need larger limits.

### CODE REVIEW

**Comment by luke-clifton** [comment]
Currently the branch is based on the v1.0.24 tag, I'll rebase it onto master tonight (and thus fix the travis build).

**Comment by stepancheg** [comment]
I'm not sure this is the right thing. Because Google's protobuf implementation (at least Java implementation) stores lengths as 32-bit integers, e. g. `readMessage` from `CodedInputStream` starts with this:

```
  public void readMessage(final MessageLite.Builder builder,
                          final ExtensionRegistryLite extensionRegistry)
      throws IOException {
    final int length = readRawVarint32(); // <-- HERE
    ...
  }
```

Although, a patch you propose keeps rust-protobuf backward compatible, messages serialized with rust-protobuf might be unparseable by other implementations of protobuf.

**Comment by luke-clifton** [comment]
Heh, oddly enough, for my use case, the data was generated by a Java program, but the number of bytes to parse is communicated out of band, and I then manually push a limit and parse length prefixed messages until the limit is reached.

The protobuf documentation seems to suggest a full sized varint could be used.

Go uses 64bit

CSharp uses 32bit
ObjectiveC uses 32bit

Seems like larger than 32bit message lengths are a bit of an edge case, but it is not that hard to stuff 4GB into a message (I've seen it done!).

If you are concerned about accidentally generating messages that can't be parsed by *some* other implementations, I could attempt to make it asymmetric. Limit the size of created messages while allowing the ability to read longer ones? It would be a shame to not be able to read messages that Go can create.

I'll wait to hear back before dedicating any time to this (my immediate problem is solved for me).

**Comment by luke-clifton** [comment]
I should note, that this is a huge abuse of protobuf messages. And it is horribly slow to parse 7GB of protobuf from a file, and I don't think we are missing out on much by not supporting it. Happy to leave this alone.

**Comment by stepancheg** [comment]
I'm not sure it is a good idea, but I applied your patch: 05b767cc8a252950887d391d820d8c02b1eb64d0 (with minor addition: I've fixed a test compilation).

Thanks!

**Pull request closed without merging**
