### PR TITLE
WIP: add a FAQ

### PR DESCRIPTION
**Pull request by nevi-me**
a FAQ draft which other contributors can add on to.

ref #304

### CODE REVIEW

**Comment by nevi-me** [comment]
I have a part below where I need some help, I'll keep tinkering locally, but haven't been able to convert a `protobuf::Message` into the type that I want.

```rust
let bytes: Vec<u8> = myBytes;

// create a protobuf::Message
let message: protobuf::Message = protobuf::parse_from_bytes().unwrap();

// TODO cleanly convert message to myproto::MyMessage

```

**Comment by stepancheg** [comment]
```
let message: MyMessageTypeNotProtobufMessage = protobuf::parse_from_bytes(&bytes)?;
```

Using `unwrap` is not the recommended way to handle errors in Rust. I can suggest reading [error handling chapter of the rust book](https://doc.rust-lang.org/book/second-edition/ch09-00-error-handling.html).

**Comment by nevi-me** [comment]
I took a shortcut, I'll `match ... {}` instead. I've updated the PR

**Comment by stepancheg** [comment]
I suggest replacing error handling with `?`, because it's standard Rust idiom.

Actually, if you like you can live questions as is (or add more questions), and I will write answers a bit later.

**Comment by nevi-me** [comment]
I've emptied out the answers. I must admit, I've rarely used `?` because I don't yet understand it. I spend a lot on the 2nd edition Rust book, so I'll get better with time.

Thanks Stepan

**Pull request closed without merging**
