### PR TITLE
Use latest protobuf and prune travis config

### PR DESCRIPTION
**Pull request by tamird**
@stepancheg

### CODE REVIEW

**Comment by stepancheg** [comment]
> right now you're on an ancient 2.2, because that's the latest version provided by travis' old ubuntu. using 2.6 means you can start adding features like anyof, allow_alias, import public, etc. (see https://github.com/google/protobuf/blob/master/CHANGES.txt)

Ubuntu 12.04 used in travis [is ancient indeed](https://github.com/travis-ci/travis-ci/issues/2046). protobuf version in Ubuntu 12.04 is 2.4.1. Anyway, 2.4.1 it is still old.

However, rust-protobuf does not need latest protoc to implement features like `anyof`. Rust-protobuf git repository contains `descriptor.proto` and generated `descriptor.rs`. That descriptor is taken from 2.5, and descriptor from 2.6 can be used instead: `descriptor.proto` from 2.6 doesn't use modern features and can be compiled even with protoc 2.4.

Modern protobuf is actually needed to implement tests for rust-protobuf (tests, which invoke protoc), but I'd rather made tests of modern protobuf features optional, rather than forced travis to download latest protobuf.

I don't like the idea of downloading protobuf from internet in travis for two reasons:
* it adds extra load to travis servers
* it makes build fragile, as build may produce false positive in case of network errors

Summary: rust-protobuf does not need latest protobuf to implement modern protobuf features.

**Comment by tamird** [comment]
I'll just leave this here until you decide that testing all functionality is more important that conserving trivial travis-ci resources (the download is < 2MB).

FWIW, this stuff is almost straight out of travis-ci's own guides http://docs.travis-ci.com/user/installing-dependencies/#Installing-Projects-from-Source.

**Comment by tamird** [comment]
rebased

**Comment by stepancheg** [comment]
Applied.

**Pull request merged**
