### PR TITLE
Travis container build

### PR DESCRIPTION
**Pull request by tamird**
@stepancheg just running travis for the moment

### CODE REVIEW

**Comment by tamird** [comment]
@stepancheg this is working - it takes total build time from ~18m to 6m

**Comment by stepancheg** [comment]
I don't understand, how disabling sudo speeds up build?

**Comment by tamird** [comment]
http://docs.travis-ci.com/user/workers/container-based-infrastructure/

**Comment by stepancheg** [comment]
Pushed.

**Comment by tamird** [comment]
sweet

**Pull request merged**
