### PR TITLE
Added traits for Repeated

### PR DESCRIPTION
**Pull request by valarauca**
I implemented a handful of `From` traits for the `Repeated` type. Also I added in the `to_vec` function which a todo comment called out. 

---

There were ~6 other files touched when I ran `cargo fmt` it was still passing tests tho.

### CODE REVIEW

**Comment by stepancheg** [comment]
Could you revert formatting please? Rustfmt is not used in rust-protobuf because of issues in rustfmt.

**Comment by valarauca** [comment]
Sorry got involved with RL stuff.

**Comment by stepancheg** [comment]
OK, I'll do that myself.

**Comment by stepancheg** [comment]
I cherry-picked first of your commits. Thanks!

**Pull request closed without merging**
