### PR TITLE
Fix invalid aliasing and uninint memory in streams

### PR DESCRIPTION
**Pull request by saethlin**
In its current state, running `cargo miri test` on this codebase flags a number of problems. This PR fixes all of those. It unfortunately does _not_ make `MIRIFLAGS="-Zmiri-tag-raw-pointers" cargo miri test` pass completely, because `bytes` has a soundness problem which I've also put up a PR to address, and is in another aspect unanalyzable (currently?) for miri.

Using `remove_lifetime_mut` to construct then hold on to both a `Vec` and a mutable slice into it violates the existing Rust aliasing rules in this particular usage pattern, because both `&mut` and `Unique<T>` (which is used to implement `Vec`) assert unique access to their contents. Though at the moment Stacked Borrows is experimental, the aforementioned properties are already relied upon by rustc, because it emits the LLVM `noalias` attribute for these types.

The only sound way to get write access beyond the end of a `Vec` is to offset a pointer from the `Vec`, and access the data either through a raw pointer or as a reference to `MaybeUninit<T>` because slices require that their contents must be properly initialized. Additionally, this access cannot be done through `get_unchecked_mut` because that method comes from the `Deref` impl on `Vec`, so it is a precondition violation to use that method to access between `len` and `capacity`.

I've tried to be somewhat surgical in what I'm changing here. Sometimes unsound constructs are used because they look simpler, so please do let me know if I should adapt the code to accomodate the valid implementation technique(s).

### CODE REVIEW

**Comment by stepancheg** [comment]
What you are saying makes sense, and thank you for detailed write up.

The issue is that I cannot reproduce it (probably I don't completely understand it).

I've set up CI job which runs [`cargo miri test -p protobuf --lib`](https://github.com/stepancheg/rust-protobuf/runs/5000841211?check_suite_focus=true). Is it possible to modify this PR with repro test case?

**Comment by stepancheg** [comment]
I clicked approve CI, github seems to not run it by default now for first-time contributors.

Also, AFAIU, if can trigger the same actions in your repository.

**Comment by saethlin** [comment]
Oh! Doing stuff on my own repo sounds good. I'm on my way to bed but if this latest push doesn't get thing rolling I'm sure I'll be in for a learning experience tomorrow.

One test which can demonstrates the above is `buf_read_iter::test_bytes::read_exact_bytes_from_bytes`. I don't know how to select the package/library that test is part of. But `cargo miri test buf_read_iter::test_bytes::read_exact_bytes_from_bytes`. I have basically no understanding of workspaces. And I know about this test, because I just do the naive thing and run `cargo miri test`, then manually whittle away tests which are problematic to run under miri.

If you're interested in running miri generally, you can use `#[cfg(miri)]` to swap in smaller values for big tests (because miri is slow) or just disable tests entirely which need things like filesystem access (doesn't work on Windows yet) or any number of things that aren't pure-Rust code. You shouldn't need to many adjustments to make it viable to just run all your tests with `cargo miri test` in CI.

**Comment by stepancheg** [comment]
> If you're interested in running miri generally, you can use #[cfg(miri)] to swap in smaller values for big tests

[Already do that!](https://github.com/stepancheg/rust-protobuf/blob/b85fc03aa717670f1137cc28bd192998f54d0ff6/protobuf/src/lazy_v2.rs#L59)

**Comment by stepancheg** [comment]
```
cargo miri test -p protobuf --lib
```

does not select the test you mentioned, but:

```
cargo miri test -p protobuf --lib --features=with-bytes
```

does.

Is bug specific to `bytes` crate/feature?

**Comment by saethlin** [comment]
Okay, I think I've sorted things out now.

I was wrong to point out that test case. All test that use `bytes` will not pass under Miri, because of https://github.com/tokio-rs/bytes/issues/522 (I also submitted a PR to `bytes` which fixes the issue, but they haven't gotten to it yet). So I've `cfg`'d out all the tests that use `bytes` under Miri.

As I mentioned in my original comment (then forgot, apparently) to detect these issues you need `-Zmiri-tag-raw-pointers`. By default, Miri uses an incomplete implementation of Stacked Borrows (which is the name of the pointer-tagging model), which is a real shame because pointers are finicky and also other problems such as creating references to uninint memory and indexing out of bounds with `get_unchecked` are accidentally detectd by Miri's Stacked Borrows checker, when `-Zmiri-tag-raw-pointers` is set.

So the invocation is
```
MIRIFLAGS=-Zmiri-tag-raw-pointers cargo miri test -p protobuf --lib
```
which I've amended the CI config to do. Without this PR, using that command you should see a failure in the test `coded_input_stream::test::test_input_stream_limits`.

**Comment by stepancheg** [comment]
OK, trying to unfold it.

First, I took `CodedOutputStream` part of the PR.

The issue with this PR is that `.buffer()` call in the PR is much more expensive with this PR: it does branches instead of computing offset.

And `.buffer()` need to be very fast, because it is called in virtually any operation, like `write_raw_varint32`.

So I tried to implement it preserving `buffer`, but making it raw pointer instead of borrowed pointer.

Can you please review #597?

**Comment by stepancheg** [comment]
OK, now I patched `CodedInputStream`: 7c70db2887d89c19569b21df3c3646e87152631f.

In your PR you zero filled the vec, which is not necessary: `BufRead` can be read into `[MaybeUninit<u8>]`, and the latter can be obtained using `vec_spare_capacity_mut`.

Test pass now (except disable slow tests and tokio-bytes tests).

Keeping the issue open because this code need to be ported to stable branch.

Thank you for the the bugreport, prototype, review and knowledge!

**Comment by stepancheg** [comment]
Version 2.27.0 contains the fixes.

**Pull request closed without merging**
