### PR TITLE
Update protoc-rust readme

### PR DESCRIPTION
**Pull request by DarkEld3r**
As far as I can see, the released version already contains the `Codegen` builder.

### CODE REVIEW

**Comment by DarkEld3r** [comment]
As far as I can see, the build failed because of cargo fmt check that isn't related to my changes. Should I fix it?

**Comment by stepancheg** [comment]
No need, thanks! (If you want to fix fmt, submit a different PR please)

**Comment by DarkEld3r** [comment]
@stepancheg It seems `#![rustfmt::skip]` doesn't work in the generated files for some reason. I will try to investigate it.

**Comment by stepancheg** [comment]
> doesn't work in the generated files for some reason

Not again! Rustfmt is a constant source of pain: it got broken several times during the last couple of years.

**Comment by DarkEld3r** [comment]
Personally I'm pretty happy with rustfmt, but I can imagine that your case is special. :upside_down_face: I have submitted the issue: https://github.com/rust-lang/rustfmt/issues/4344

**Comment by stepancheg** [comment]
Thanks!

**Pull request merged**
