### PR TITLE
remove #[feature(core)] and #![feature(collections)] => stable compliant!

### LINKED ISSUE #94: Doesn't compile with 1.0.0 beta.
src/lib/protobuf.rs:2:1: 2:33 error: unstable feature
src/lib/protobuf.rs:2 #![feature(box_patterns, alloc)]
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: this feature may not be used in the beta release channel
src/lib/protobuf.rs:5:1: 5:25 error: unstable feature
src/lib/protobuf.rs:5 #![feature(collections)]
                      ^~~~~~~~~~~~~~~~~~~~~~~~
note: this feature may not be used in the beta release channel
src/lib/protobuf.rs:6:1: 6:21 error: unstable feature
src/lib/protobuf.rs:6 #![feature(convert)]
                      ^~~~~~~~~~~~~~~~~~~~
note: this feature may not be used in the beta release channel
src/lib/protobuf.rs:7:1: 7:18 error: unstable feature
src/lib/protobuf.rs:7 #![feature(core)]
                      ^~~~~~~~~~~~~~~~~
note: this feature may not be used in the beta release channel
src/lib/protobuf.rs:8:1: 8:22 error: unstable feature
src/lib/protobuf.rs:8 #![feature(str_char)]
                      ^~~~~~~~~~~~~~~~~~~~~
note: this feature may not be used in the beta release channel
error: aborting due to 5 previous errors
Could not compile `protobuf`.

### PR DESCRIPTION
**Pull request by TeXitoi**
* make core.rs stable compatible by using generated as_any method
* remove usage of unstable std::iter::Iterator::sum()
* remove Singular[Ptr]Field::as_[mut_]slice()
* remove #![feature(collections)] by copying escape_default() into source

fix #94 \o/

### CODE REVIEW

**Comment by TeXitoi** [comment]
tests are not yet stable compliant, working on it.

**Comment by TeXitoi** [comment]
Tests are stable compliant. OK?

**Comment by icorderi** [comment]
+1

**Comment by stepancheg** [comment]
Thanks!

**Pull request merged**
