### PR TITLE
Codegen: option to use BTreeMap as map representation

### PR DESCRIPTION
**Pull request by akhramov**
As of now, protobuf maps are represented with
[std::collections::HashMap](https://doc.rust-lang.org/stable/std/collections/struct.HashMap.html), which serves as a robust default. In rarer instances, opting for a different implementation, such as BTreeMap, might be desirable, e.g. for deterministic serialization.

This change

* adds `btreemaps` codegen option to generate [std::collections::BTreeMap](https://doc.rust-lang.org/std/collections/struct.BTreeMap.html) for maps representation.

### CODE REVIEW

**Comment by akhramov** [comment]
(reopened #696, sorry for the noise)

**Comment by stepancheg** [comment]
I think changes in `.github/workflows/ci.yml` should be reverted.

**Comment by stepancheg** [comment]
Also we don't need a separate crate for test. Instead, code should be customized for single test file within test suite.

**Comment by akhramov** [comment]
> I think changes in .github/workflows/ci.yml should be reverted.

Absolutely.

> Also we don't need a separate crate for test. Instead, code should be customized for single test file within test suite.

Not sure if I got you right, wdyt of the current approach?

**Comment by stepancheg** [comment]
There are options like [tokio_bytes](https://docs.rs/protobuf-codegen/latest/protobuf_codegen/struct.Customize.html#method.tokio_bytes) to change codegen behavior. Change to `BTreeMap` should done similarly.

**Comment by akhramov** [comment]
Yup, that's what this PR does now.

**Comment by stepancheg** [comment]
Working on this PR, merging parts of this, this is why it shows merge conflict now.

**Comment by stepancheg** [comment]
OK, merged.

Now need to either merge to stable branch or create new stable branch.

**Pull request closed without merging**
