### PR TITLE
gen_mod_rs codegen option

### PR DESCRIPTION
**Pull request by stepancheg**
When this option is specified, codegens generate `mod.rs` which
`pub use` all the generated files.

For the test included in this PR, generated `$OUT_DIR/include_generated/mod.rs` contains:

```
// @generated

pub mod v2;
pub mod v3;
```

This way:
* users can include generated files
* users don't have to enumerate generated files
* this opens a door to generating a mod hierarchy (`foo::bar` for `foo/bar.proto`)

If you want to review this diff (and please do review!) start with looking at `protobuf-test/src/include_generated/mod.rs` in this PR.

`gen_mod_rs` option can be specified
* in `Customize` struct when codegen is invoked programmatically
* or with command-line option `protoc --rust_opt=gen_mod_rs=true --rust_out=...` when invoking `protoc` command

When landed this option will be backported to the stable branch (v2), and likely will be on by default in the next stable version (v3).

### CODE REVIEW

**Comment by clintfred** [comment]
Will this also apply to `protubuf-codegen-pure`?

**Comment by stepancheg** [comment]
Yes, it will be available for all three ways to generate protobuf files: `protoc-gen-rust` plugin, `protoc-rust` and `protobuf-codegen-pure`.

**Comment by stepancheg** [comment]
a9f694aaf0f6802d10dec0d453831a88ca6c595c is in 2.18 branch. To be released soon.

**Comment by stepancheg** [comment]
2.18.0 released.

**Pull request merged**
