### PR TITLE
some enhancement of check_initialized

### PR DESCRIPTION
**Pull request by liuchong**
1. report not initialized fields in the result error message.
2. return a FieldError when missing fields, instead of just panic.

### CODE REVIEW

**Comment by stepancheg** [comment]
That would be useful change, but should be made somewhat differently. I've made a partial commit: 51d56819c6cdaffc88bafe3f4048e02bb273603f.

`is_initialized` should still return `bool`, and `check_initialized` should return `Result`. Generated code should override `check_initialized` and for backward compatibility should override `is_initialized`.

Note, that `ProtobufError` should not contain `String` fields, because `String` is expensive. It was a design error in previous versions, and new enum variants should avoid heap allocations.

**Comment by liuchong** [comment]
Your solution look good, let me close it.

**Comment by stepancheg** [comment]
It does not show which field is not initialized.

**Comment by liuchong** [comment]
Eh...sorry, network is somehow slowly, let me check on monday and have a try :blush:

**Pull request closed without merging**
