### PR TITLE
stream: use static dispatch for CodedInputStream

### PR DESCRIPTION
**Pull request by BusyJay**
This pr use static dispatch for CodedInputStream. According to the perf test, there are some significant improvements in various cases.

### master:
test1: write: 77 ns per iter
test1: read: 97 ns per iter
test1: read reuse: 92 ns per iter
test_repeated_bool: write: 69 ns per iter
test_repeated_bool: read: 165 ns per iter
test_repeated_bool: read reuse: 125 ns per iter
test_repeated_packed_int32: write: 102 ns per iter
test_repeated_packed_int32: read: 217 ns per iter
test_repeated_packed_int32: read reuse: 165 ns per iter
test_repeated_messages: write: 235 ns per iter
test_repeated_messages: read: 1171 ns per iter
test_repeated_messages: read reuse: 327 ns per iter
test_optional_messages: write: 205 ns per iter
test_optional_messages: read: 535 ns per iter
test_optional_messages: read reuse: 325 ns per iter
test_strings: write: 118 ns per iter
test_strings: read: 376 ns per iter
test_strings: read reuse: 172 ns per iter
test_small_bytearrays: write: 274 ns per iter
test_small_bytearrays: read: 251 ns per iter
test_small_bytearrays: read reuse: 130 ns per iter
test_large_bytearrays: write: 20139 ns per iter
test_large_bytearrays: read: 10893 ns per iter
test_large_bytearrays: read reuse: 7678 ns per iter

### opt-is:
test1: write: 78 ns per iter
test1: read: 59 ns per iter
test1: read reuse: 52 ns per iter
test_repeated_bool: write: 86 ns per iter
test_repeated_bool: read: 114 ns per iter
test_repeated_bool: read reuse: 65 ns per iter
test_repeated_packed_int32: write: 134 ns per iter
test_repeated_packed_int32: read: 134 ns per iter
test_repeated_packed_int32: read reuse: 71 ns per iter
test_repeated_messages: write: 199 ns per iter
test_repeated_messages: read: 1003 ns per iter
test_repeated_messages: read reuse: 166 ns per iter
test_optional_messages: write: 190 ns per iter
test_optional_messages: read: 362 ns per iter
test_optional_messages: read reuse: 165 ns per iter
test_strings: write: 123 ns per iter
test_strings: read: 246 ns per iter
test_strings: read reuse: 109 ns per iter
test_small_bytearrays: write: 259 ns per iter
test_small_bytearrays: read: 219 ns per iter
test_small_bytearrays: read reuse: 93 ns per iter
test_large_bytearrays: write: 19579 ns per iter
test_large_bytearrays: read: 12098 ns per iter
test_large_bytearrays: read reuse: 6702 ns per iter

This pr break Message into Message and CodedMessage, which will require users to **use CodedMessage explicitly** once they upgrade protobuf. Old generated code will **not work** if this pr is merged.

I have no idea what format rules this project follows, so I haven't formatted the code yet, any suggestions?

I also changed CodedOutputStream to static dispatch too, but it's not included in the pr, because I see performance decrease in some cases. I will fire another pr once I figure it out.

### CODE REVIEW

**Comment by stepancheg** [comment]
I think there is too much noise in tests. You patch didn't modify write code, however, test results for write also change. E. g.

```
test_repeated_bool: write: 69 ns per iter
test_repeated_bool: write: 86 ns per iter

test_repeated_packed_int32: write: 102 ns per iter
test_repeated_packed_int32: write: 134 ns per iter

test_repeated_messages: write: 235 ns per iter
test_repeated_messages: write: 199 ns per iter

test_optional_messages: write: 205 ns per iter
test_optional_messages: write: 190 ns per iter

test_small_bytearrays: write: 274 ns per iter
test_small_bytearrays: write: 259 ns per iter
```

I don't believe dynamic dispatching is the main performance issue, and performance improvements should be significant to compilate API for users.

**Comment by BusyJay** [comment]
I can see the performance increase constantly when running the perftest repeatedly. You should also be able to reproduce it on your machine.

According to our own bench of a product, which does a lot of protobuf encode and decode and CPU is the bottleneck, performance increases about 15% after switching to the static dispatch branch.

**Comment by stepancheg** [comment]
I think parsing could be implemented efficiently without making dispatching static, but with a bit of `unsafe` code.

`CodedInputStream` could cache result of `InputSource.fill_buf` in a field.

This approach has two drawbacks:

1. You need `unsafe` code, because you cannot safely store `fill_buf` result in a field.
* It is practially safe for `BufRead` and `&[u8]` param, because they are unmovable, because `CodedInputStream` holds a reference to that class.
* It is practically safe for `InputSource::Read(BufReader<&'a mut Read>)` variant, because
** we _know_ that `BufReader` buffer is not moved when `BufReader` is moved
** or alternatively, we can allocate `BufReader` in a box
** or we can have own implementation of `BufReader`.

2. User API will need something like `flush()` operation that would call `consume` on the underlying buffer in case `CodedInputStream` created from `BufRead`. This operation could be called from `CodedInputStream` destructor, but it is still a breaking change and a couple of client projects could be broken.

**Comment by BusyJay** [comment]
I think static dispatch way is more clean and elegant. When using static dispatch, the compiler figures out more possible improvements and handles all the inline and opt out things automatically. And the magic happens safely.

I personally don't think it's a good idea to keep a buffer inside library. I think it's caller's choices to choose buffer or not. Usually the Reader/Writer itself includes a buffer already.

**Comment by stepancheg** [comment]
> I think static dispatch way is more clean and elegant.

It makes API harder to use, slows down compilation and increases binary size.

> I personally don't think it's a good idea to keep a buffer inside library. I think it's caller's choices to choose buffer or not. Usually the Reader/Writer itself includes a buffer already.

In that case you can call `CodedInputStream::from_buffered_reader` and protobuf won't allocate own buffer. `CodedInputStream` will just store result of `fill_buf`, a pointer to the buffer.

**Comment by BusyJay** [comment]
> It makes API harder to use, ...

Actually, after the changes, users only need to include `CodedMessage` trait, all the other things are the same as it used to be.

**Comment by stepancheg** [comment]
Reads do not (usually) call virtual functions now: f7dc5f02ddb5eeec16a0a933f8a6071dd98778a3.

I did as I proposed in my previous message. Although implementation now contains `unsafe` code and relies on `BufReader` implementation details, I think it is OK.

**Comment by siddontang** [comment]
@stepancheg 

Can we use the same `unsafe` way to handle CodedOutputStream?

**Comment by stepancheg** [comment]
@siddontang `CodedOutputStream` has no issue with virtual dispatch, because `CodedOutputStream` is buffered. However, it has an issue with double-buffering.

I assume that `CodedOutputStream` needs access to write buffer for performance. So we have four cases then:

* underlying `Write` is not buffered. Everything's right, `CodedOutputStream` does the buffering.
* underlying `Write` is actually a wrapper around around `[u8]`, which writes to that area. This issue needs to be fixed by adding another constructor in `CodedOutputStream` which should accept `&[u8]` and use it as buffer (with a bit of `unsafe` code).
* underlying `Write` is buffered and written message is large (say, 100K). Is not an issue, because `BufWriter` (and probably other implementations of buffered writers) skips internal buffering on large writes.
* underlying `Write` is buffered and written data is small (e. g. 1K). There's nothing can be done here, because Rust has no `BufWrite` trait, and even `BufWriter` (unlike `BufRead`) does not provide access to its buffer.

**Comment by stepancheg** [comment]
`CodedOutputStream::bytes` constructor is added in 035d82c80bdbfb55ecdfae97c7a321620e267842.

**Comment by stepancheg** [comment]
`CodedOutputStream::vec` constructor added: 5773985563e7ceb5efca1ffb3ea3421f79e83356.

**Comment by danburkert** [comment]
> I assume that CodedOutputStream needs access to write buffer for performance.

Could you elaborate on this assumption?  `CodedOutputStream` does not currently make use of the interior buffer, but maybe you have something as-of-yet unimplemented in mind.

The biggest performance issue I've run into with this library is the overhead of the internal buffering in `CodedOutputStream`.  By removing the internal buffering, `rust-protobuf` can be more performant and easier to use, as prototyped in #199 .

**Comment by siddontang** [comment]
Hi @danburkert 

@stepancheg supplies a `bytes` and `vec` constructors which don't create the internal buffer and I think it is better to keep the API backward compatibility.

Can we use another `ButWriter` trait to fix the `underlying Write is buffered` case?

**Comment by danburkert** [comment]
> @stepancheg supplies a bytes and vec constructors which don't create the internal buffer and I think it is better to keep the API backward compatibility.

The `vec` constructor does create an internal buffer, the `Vec`.  The `bytes` constructor is better, but it's not quite as ergonomic as serializing directly to a `Write` instance.  It also doesn't work for cases where you are trying to write to non-contiguous buffers.


> Can we use another ButWriter trait to fix the underlying Write is buffered case?

Why?  What's the problem with just writing directly to a `Write`?

**Comment by siddontang** [comment]
Hi @danburkert 

> Why? What's the problem with just writing directly to a Write?

I guess @stepancheg doesn't want to break the API, so I think maybe we can supply other construct functions.

**Comment by stepancheg** [comment]
@danburkert 

> The vec constructor does create an internal buffer, the Vec.

Not it doesn't. It uses `Vec` provided by user, and `CodedOutputStream.buffer` is a reference to that `Vec` data.

**Comment by stepancheg** [comment]
@siddontang 

> Can we use another ButWriter trait to fix the underlying Write is buffered case?

Something similar to `BufRead` trait:

```
trait BufWrite : Write {
    fn buffer(&mut self) -> &mut [u8];
    fn commit(&mut self, amount: usize) -> io::Result<()>;
}
```

It could be added to the rust-protobuf, but user would need to implement it.

**Comment by stepancheg** [comment]
> Why? What's the problem with just writing directly to a Write?

I think writing directly to byte array can be faster that writing to `Write` byte at a time (for example, when you writing varint which can be 1 to 10 bytes long.

This is how it is done in Java [and C++ implementations of protobuf](https://github.com/google/protobuf/blob/master/src/google/protobuf/io/coded_stream.h#L1264): if you know that buffer has at least 10 bytes available (it is true most of the time), that you can write directly to that array, otherwise you need to do a sequence of single byte writes, or create a 10 bytes array on the stack, write to it and then write that array to the `Write` performing unnecessary copying and a loop.

Rust-protobuf doesn't have this optimization, but it should.

**Comment by danburkert** [comment]
> Not it doesn't. It uses Vec provided by user, and CodedOutputStream.buffer is a reference to that Vec data.

OK fair enough.  The issue is, however, that only helps if the application is trying to serialize into a `Vec`. In my case I want to serialize into a [netbuf](https://github.com/tailhook/netbuf) buffer, and many applications using mio/tokio often want to serialize into a [bytes](https://crates.io/crates/bytes) buffer.  In general, you are never going to be able to add a variant for all of the different buffer abstractions.  That's exactly *why* the `Write` abstraction exists.

> create a 10 bytes array on the stack, write to it and then write that array to the Write performing unnecessary copying and a loop.

That sounds like a great optimization to me, the extra copy of up to 10 bytes from a stack allocated array is going to be extremely cheap (as opposed to having to copy all strings and variable length fields again, as I would currently have to do to serialize into a `netbuf`).  Not sure what you mean by an extra loop.

If cutting out that small copy for varints is really that important, then I think it can still be done by specializing the `CodedOutputStream` trait for `Vec` or maybe `AsMut<[u8]>`.

**Comment by danburkert** [comment]
Or, even more simply, do an initial check to see if the varint can be serialized to 1 byte, and if so do it directly.  I imagine most varint serialization is done for tags, and most tags are done in a single byte.

**Comment by stepancheg** [comment]
@danburkert 

> extra copy of up to 10 bytes from a stack allocated array is going to be extremely cheap

It is extremly cheap, but extremely frequent.

> even more simply, do an initial check to see if the varint can be serialized to 1 byte, and if so do it directly. I imagine most varint serialization is done for tags, and most tags are done in a single byte.

It depends on your data. Sometimes you have integer fields (e. g. enums). Every message or string starts with varints. Sometimes you have fields with numbers above 16, so tags occupy more than one byte.

>  Not sure what you mean by an extra loop.

`memcpy` within buffered `Write` implementation after a loop which populates 10-bytes buffer.

>  That's exactly why the `Write` abstraction exists.

No, that's why [abstractions like ZeroCopyOutputStream exist](https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.io.zero_copy_stream#ZeroCopyOutputStream.Next.details). Rust standard library provides no such abstraction.

But as I said earlier, `BufWrite` abstraction could be added to rust-protobuf. So `BufWrite` could be implemented for bytes and netbuf (and for `Vec`).

Will that work for you?

**Comment by danburkert** [comment]
I think we're at an impasse.  If you aren't willing to break backwards compat I'll continue maintaining a fork.

**Comment by stepancheg** [comment]
@danburkert 

> I think we're at an impasse.  If you aren't willing to break backwards compat I'll continue maintaining a fork.

Could you be a little more constructive, please?

I've proposed a solution: `BufWrite` trait. Will it work for you? If it won't could you please explain why?

If it won't, probably we will think of something else.

It is a backward compatibility issues, but I also honestly think that current state of `CodedOutputStream` is the best API choice even if project started from scratch. Because of its simplicity: you do not need to make every function generic.

**Comment by danburkert** [comment]
Sure,

For `BufWrite` to work it would need to be in the standard library.  Otherwise it's unreasonable to expect the `netbuf` or any other buffer abstraction crate to implement it.  Likewise, it's unreasonable to expect you to implement it for every odd buffer abstraction out there.  As a consumer of netbuf and protobuf, my application can't implement it due to coherence rules.

Secondly, `BufWrite` isn't (and probably never will be) in the stdlib because it's a poor abstraction when combined with the safety guarantees that Rust likes to provide.  To implement it, buffers would need to fully initialize returned memory, which makes the abstraction useless because the extra memset negates the advantages of cutting out a memcpy.

> I also honestly think that current state of CodedOutputStream is the best API choice even if project started from scratch. Because of its simplicity: you do not need to make every function generic.

Have you read #199?  The API is simpler than the current API.  For example, the awkward `with_coded_output_stream` function is no longer needed and has been removed. The API now works with any `Write` instance, no need to wrap it in a `CodedOutputStream` as an intermediate step.  It stops the proliferation of `write_to_<blah>` functions.

With regards to making serialization methods on `Message` take a type param - I agree with you.  It's important to me that `Message` remains object-safe, so type params can't be used.  #199 doesn't change that.

**Comment by danburkert** [comment]
The type params on `ProtobufType` can be changed back to trait objects; that was an oversight in the PR.

**Comment by stepancheg** [comment]
@danburkert

> The type params on ProtobufType can be changed back to trait objects; that was an oversight in the PR.

If that was an oversight, could you please fix that PR to avoid misunderstanding?

**Comment by danburkert** [comment]
Sure, I can do that in the next few days.

**Comment by stepancheg** [comment]
I assume that static dispatching is no longer necessary, because `CodedInputStream` caches result of `BufWriter.write`. So I'm closing the issue.

**Pull request closed without merging**
