### PR TITLE
Fix many inconsistencies in protoc-codegen-pure

### PR DESCRIPTION
**Pull request by benesch**
See individual commit messages for details—I've worked hard to make each commit meaningful! The basic gist is to diff `protoc-rust` and `protoc-codegen-pure` output on all the test files, and fix the inconsistencies one by one. This can merge as-is, though, as the test allows marking files as known failures.

Thanks for all your work on this library, @stepancheg!

### CODE REVIEW

**Comment by benesch** [comment]
Hey @stepancheg, any chance you can take a look at this? I can split it into multiple PRs if that would be easier.

**Comment by stepancheg** [comment]
Hi @benesch! Thank you for the PR!

Yes, splitting into different PRs would help, I read this PR, it contains not obvious parts.

**Comment by benesch** [comment]
Sure, no problem! I've started the process in #502.

**Comment by benesch** [comment]
Some of this landed in #502. I'll be opening additional bite-sized PRs for the rest.

**Pull request closed without merging**
