### PR TITLE
Treat paths as impl AsRef<Path>

### LINKED ISSUE #366: Args structure should use Paths instead of &strs
Currently the protobuf_codegen_pure::Args and protobuf_codegen::Args uses &str for file references which is 1) technically incorrect and 2) not very convenient because user-side conversions are needed.

As far as I see the implementation converts to Path internally anyway. So I'd propose to change the file-related Args fields to generic `<P: AsRef<Path>>` so the existing code won't be broken.

### LINKED ISSUE #380: question: protoc Args ergonomics
relevant code: https://github.com/stepancheg/rust-protobuf/blob/aa54d71d023861d2661f487bf5db5a38157b8003/protoc/src/lib.rs#L15-L40

use case: i want to automatically generate a list of input files based on all files in a given directory. 

current implementation:
```rust
let input_files: Vec<String> = fs::read_dir(Path::new("protos"))
    .expect("could not read protos directory")
    .map(|dir_entry| {
        dir_entry.expect("unable to get entry")
            .path()
            .display()
            .to_string()
    })
    .collect();
let input_files: Vec<&str> = input_files.iter()
    .map(|x| x.as_ref())
    .collect();
protoc_rust::run(protoc_rust::Args {
    out_dir: PROTO_OUTPUT_DIR,
    input: input_files.as_slice(),
    includes: &["protos"],
    customize: Customize {
        expose_oneof: Some(true),
        serde_derive: Some(true),
        ..Default::default()
    },
}).expect("protoc");
```

this seems sort of awkward, and took me a while to figure out the proper way to get `Vec<String>` converted into `&[&str]` (maybe because i'm a rust noob) ([relevant stackoverflow](https://stackoverflow.com/questions/41179659/convert-vecstring-into-a-slice-of-str-in-rust?rq=1)). is there a reason not to use `Vec<String>`? it seems in this case, ergonomics may outweigh performance optimizations.

unsure if it's worth making a backward incompatible change though.

### PR DESCRIPTION
**Pull request by dtolnay**
### *TODO:*

- [ ] *If there is agreement on the approach, I will follow up with more thorough documentation of the new public API*

Fixes #366. Fixes #380.

---

APIs in terms of Path are more convenient for build scripts that programmatically construct paths to input files or include-directories using the std::path library. As an example of such code, Chromium OS contains the following in one of its build scripts:

```rust
let proto_root = match env::var("SYSROOT") {
    Ok(dir) => PathBuf::from(dir).join("usr/include/chromeos"),
    // Make this work when typing "cargo build" in platform2/vm_tools/crostini_client
    Err(_) => PathBuf::from("../../system_api"),
};

let concierge = proto_root.join("dbus/vm_concierge/service.proto");
let cicerone = proto_root.join("dbus/vm_cicerone/service.proto");
let seneschal = proto_root.join("dbus/seneschal/service.proto");
let input_files = [concierge, cicerone, seneschal];
```

In order to pass those paths along to protoc_rust, they require an ugly and panicky conversion from Path to &str.

```rust
fn paths_to_strs(paths: &[PathBuf]) -> Vec<&str> {
    paths
        .iter()
        .map(|p| p.as_os_str().to_str().unwrap())
        .collect()
}

protoc_rust::Args {
    input: &paths_to_strs(&input_files),
    ...
}
```

This commit adjusts the API of protoc_rust and other entry points to accept AsRef\<Path\> as the first-class type of anything that represents a filesystem path.

In order to preserve convenient support for the common case of hardcoded string literal paths, we change code that used to use Args as a struct literal into a builder instead. This aligns with the API of the `cc` crate, and is similar to the std::process::Command API as well.

#### Before:

```rust
protoc_rust::run(protoc_rust::Args {
    out_dir: "src/protos",
    input: &["protos/a.proto", "protos/b.proto"],
    includes: &["protos"],
    customize: Customize::default(),
}).expect("protoc");
```

#### After:

```rust
protoc_rust::Args::new()
    .out_dir("src/protos")
    .inputs(&["protos/a.proto", "protos/b.proto"]),
    .include("protos")
    .run()
    .expect("protoc");
```

The relevant builder method signatures are:

```rust
impl Args {
    fn new() -> Self;
    fn out_dir(&mut self, out_dir: impl AsRef<Path>) -> &mut Self;
    fn include(&mut self, include: impl AsRef<Path>) -> &mut Self;
    fn includes(&mut self, includes: impl IntoIterator<Item = impl AsRef<Path>>) -> &mut Self;
    fn input(&mut self, input: impl AsRef<Path>) -> &mut Self;
    fn inputs(&mut self, inputs: impl IntoIterator<Item = impl AsRef<Path>>) -> &mut Self;
    fn customize(&mut self, customize: Customize) -> &mut Self;
    fn run(&self) -> Result<()>;
}
```

### CODE REVIEW

**Comment by stepancheg** [comment]
Since this is a popular request, I think I have to merge it.

Thank you for the very good quality of this PR.

Note, this change is backwards incompatible, we need to either wait till next major release (which should happen not earlier than in a couple of months) or think of a backward compatible way to do it.

**Comment by stepancheg** [comment]
I just realized that this diff updated readmes so it's now inconvenient for users using stable rust-protobuf.

I'm going to update readmes now to be compatible with the stable version.

**Comment by ashthespy** [comment]
> Since this is a popular request, I think I have to merge it.
> 
> Thank you for the very good quality of this PR.
> 
> Note, this change is backwards incompatible, we need to either wait till next major release (which should happen not earlier than in a couple of months) or think of a backward compatible way to do it.


@stepancheg This seems to have snuck into the 2.x with out a major release bump?

**Comment by stepancheg** [comment]
@ashthespy 

> This seems to have snuck into the 2.x with out a major release bump?

Kind of: in 2.x version existing `Args` object kept as deprecated and separate object `Codegen` introduced.

**Comment by ashthespy** [comment]
Okay, we shall pin even the minor version as an interim solution. 
Our actual issue derives from #386 - as there wasn't a parsing api exposed, so we used `parse_and_typecheck`.. If you have ideas for this, all ears!

**Pull request merged**
