### PR TITLE
V2 with serde

### PR DESCRIPTION
**Pull request by bacek**
Add "with-serde" feature based on #323.

Changes from original PR:

1. Path protobuf-codegen to emit serde derive/skip directives
2. Skip CachedSize ser/de totally.

### CODE REVIEW

**Comment by stepancheg** [comment]
What's your use-case of serde for rust-protobuf?

I have doubts about serde. Serde creates several complications for rust-protobuf and I don't know what's the best approach to solve them.
* if only JSON serialization is needed, then rust-protobuf (in master) supports JSON serialization natively
* if only user types need to be serialized (not types from `descriptor.proto` which are part of rust-protobuf), then probably [hooks should be enough](https://github.com/stepancheg/rust-protobuf/issues/338)
* also, rust-protobuf now has runtime-reflection (text format and json is implemented using it), probably Serde can be implemented using runtime reflection in user code (or in a separate crate)

**Comment by stepancheg** [comment]
> What kind of complication serde creates with my approach?

Mainly questions about API:
* what are codegen options?
* what are annotation conditions?
* possible future backwards-compatibility issues

> Apart from that "consumer code" has to declare

Consumers also need to declare an option to "unhide" serde annotations in generated code.

> I did try to implement with_serde in Customize too. Didn't quite work.

Not sure what could be wrong. BTW, FYI, `protoc-gen-rust` plugin is now [able to pass options to codegen](https://github.com/stepancheg/rust-protobuf/commit/7ebf32b47cb18160752a943dccb9d0d7ecdf91ed).


Anyway, I've updated master with parts of your PR.

The main difference is that version in master explicitly requires option `serde_derive = true` to be specified in order to generate serde annotations, although generated serde annotations are still guarded with `#[cfg_attr(feature = "with-serde", ...)]`.

Before merging this change to a 2.0 branch (or rather to 2.1 branch), following questions need to be answered:
* do we need a codegen option `serde_derive`, or annotations should be on by default?
* if there's a codegen option, do we need a `#[cfg_attr(...)]` guard?
* if we use `#[cfg_attr(...)]`, what should it check? Alternatives are: `#[cfg_attr(feature = "with-serde", ...)]`, `#[cfg_attr("protobuf-serde", ...)]` or as codegen option

I think `#[cfg_attr("protobuf-serde", ...)]` is more flexible (because it does not require exposing generated code internals as a crate "feature", but requires a line like this added to `build.rs`: `println!("cargo:rustc-cfg=protobuf-serde");`

**Comment by bacek** [comment]
On Mon, 1 Oct 2018 at 14:03 Stepan Koltsov <notifications@github.com> wrote:

> What kind of complication serde creates with my approach?
>
> Mainly questions about API:
>
>    - what are codegen options?
>
> I can think only of only one codegen option: "serde feature guard name" or
something along the line. Because codegen is used both for rust-protobuf
itself and consumer part. If I as consumer want to override "with_serde"
with something else. If it's absent (default) then serde derive isn't
added. Otherwise it's added guarded by #[cfg_attr].

OTOH, maybe "unconditional serde macros" can be also be used instead (off
by default). So when we generate files for rust-protobuf it emits
#[cfg_attr(feature = "with_serde")], but on consumer side I can switch on
"unconditional serde" and then codegen will just emit #[derive(Deserialize,
Serialize).]


>
>    - what are annotation conditions?
>
> Always on? It's either behind "cfg_attr" or rust-protobuf feature.


>
>    - possible future backwards-compatibility issues
>
> Can you elaborate? What kind of issues?



>
>
> Apart from that "consumer code" has to declare
>
> Consumers also need to declare an option to "unhide" serde annotations in
> generated code.
>
I start thinking that having "unconditional serde" flag for protobuf has
some merits.


> I did try to implement with_serde in Customize too. Didn't quite work.
>
> Not sure what could be wrong. BTW, FYI, protoc-gen-rust plugin is now able
> to pass options to codegen
> <https://github.com/stepancheg/rust-protobuf/commit/7ebf32b47cb18160752a943dccb9d0d7ecdf91ed>
> .
>
> Anyway, I've updated master with parts of your PR.
>
> The main difference is that version in master explicitly requires option serde_derive
> = true to be specified in order to generate serde annotations, although
> generated serde annotations are still guarded with #[cfg_attr(feature =
> "with-serde", ...)].
>
> Before merging this change to a 2.0 branch (or rather to 2.1 branch),
> following questions need to be answered:
>
>    - do we need a codegen option serde_derive, or annotations should be
>    on by default?
>
> Off by default. In both codegen approaches.

>
>    - if there's a codegen option, do we need a #[cfg_attr(...)] guard?
>
> See above.


>
>    - if we use #[cfg_attr(...)], what should it check? Alternatives are: #[cfg_attr(feature
>    = "with-serde", ...)], #[cfg_attr("protobuf-serde", ...)] or as
>    codegen option
>
> I think #[cfg_attr("protobuf-serde", ...)] is more flexible (because it
> does not require exposing generated code internals as a crate "feature",
> but requires a line like this added to build.rs:
> println!("cargo:rustc-cfg=protobuf-serde");
>
 I have no strong opinion on that one. They are both equivalent for my
end-user point of view.

**Comment by bacek** [comment]
Looks good. "Ship it!"

**Comment by bacek** [comment]
Closing if favour of master branch approach.

**Pull request closed without merging**
