### PR TITLE
Fixed compile error

### PR DESCRIPTION
**Pull request by mathewprokos**
Removed use of &str::to_ascii in decode_hex

### CODE REVIEW

**Comment by stepancheg** [comment]
I've merged your PR, thanks.

However, there's another compilation error due to recent rust changes, that's not easy to fix.

**Comment by mathewprokos** [comment]
I see that. looking at it now =/

Pretty new to rust so taking a bit to grok what is going on.

something about using not being able to use self in an object-safe trait
because the type of self could change.

**Comment by stepancheg** [comment]
No, it's not because type of self could not change. It's because static methods could not be called only using concrete type.

I think Rust is wrong in that place. In my opinion, error should arise at place where you are trying to call these functions, not at place you are declaring a variable of trait type.

**Comment by stepancheg** [comment]
Almost done it.

**Comment by stepancheg** [comment]
Finally fixed in fbe150b89638a4b2d1bbc5319a05a7f502bf6cdf.

**Comment by mathewprokos** [comment]
Awesome!

**Pull request closed without merging**
