### PR TITLE
remove unnecssary write buffer

### PR DESCRIPTION
**Pull request by siddontang**
Hi @stepancheg 

For #186 

+ Remove inner buffer for CodedOutputStream
+ Use BufWriter for Write
+ Don't use buffer for Vector 
+ Format codes with rustfmt 0.6.0

### CODE REVIEW

**Comment by stepancheg** [comment]
I have two comments about this PR:

1. You need to separate code formatting changes from behavior changes.

2. I'm not sure that with this patch code is not going to be slower. For example, when you are writing varint encoded as 10 bytes, new implementation will do 10 virtual calls to `Write` trait. I'm not sure if it a big deal or not, but if you think that it does not affect performance, benchmarks are needed.

**Comment by siddontang** [comment]
Well, I will use another PR for format first and do some benchmark later.

**Comment by siddontang** [comment]
> new implementation will do 10 virtual calls to Write trait

Sorry that I don't understand it, why virtual call here? We have no Box here only a trait, does Rust not determine the really type when compiles?

**Comment by stepancheg** [comment]
`CodedOutputStream` holds a pointer to `Write`, it is not parameterized by `Write`, so calls to `Write` are dynamically dispatched.

And another remark. If `CodedOutputStream` buffer capacity exceeds `BufWriter` buffer capacity, then `BufWriter` buffer is effectively unused due to this part in rust src:

```
impl<W: Write> Write for BufWriter<W> {
    fn write(&mut self, buf: &[u8]) -> io::Result<usize> {
        if self.buf.len() + buf.len() > self.buf.capacity() {
            self.flush_buf()?;
        }
        if buf.len() >= self.buf.capacity() {
            self.panicked = true;
            let r = self.inner.as_mut().unwrap().write(buf);
            self.panicked = false;
            r
        } else {
            Write::write(&mut self.buf, buf)
        }
    }
    ...
}
```

So `CodedOutputStream` should probably increase default buffer size (which is 4096 now, and `BufWriter` default is 8192).

**Comment by stepancheg** [comment]
I've increased default buffer size: c69b137321e5b762cc5b5ed731432c73a35fc6ed.

**Comment by siddontang** [comment]
Got it

**Pull request closed without merging**
