### PR TITLE
Remove unused attribute

### PR DESCRIPTION
**Pull request by tamird**
@stepancheg missed when you grabbed my branch

### CODE REVIEW

**Comment by stepancheg** [comment]
Without this attribute, compiler emits a warning:

```
lib/codegen.rs:35:5: 35:24 warning: variant is never used: `Uniq`, #[warn(dead_code)] on by default
lib/codegen.rs:35     Uniq(Box<RustType>),
                      ^~~~~~~~~~~~~~~~~~~
```

**Comment by tamird** [comment]
I dont get that warning (it's used in the `Debug` impl)

**Comment by tamird** [comment]
No warning in the travis build either

**Comment by stepancheg** [comment]
Strange. I don't see it now either. Probably I used outdated version of rust compiler before.

Merged.

**Pull request merged**
