### PR TITLE
Fixes crashing assert in bit_read_iter

### LINKED ISSUE #208: Protobuf deserialization crashes at runtime when the payload ends by a 10 bytes long vint_u64
The assertion in `buf_read_iter` is triggered when reading a payload in which the very last thing 
to deserialize is a 10 bytes long variable u64 int. (For instance if the value is actually a signed int like -1u32).

In that case, `read_raw_varint64` will take the "fast track" branch as the buffer still contains the maximum possible of 10 bytes.

After deserialization, `consume` is called. Unfortunately the assert condition is wrong and fails the code.

### PR DESCRIPTION
**Pull request by fulmicoton**
Closes #208

### CODE REVIEW

**Comment by stepancheg** [comment]
Could you please also add a test? Or I could add it myself a bit later.

**Comment by fulmicoton** [comment]
I added a unit test that panicks without the patch and works after adding the patch.

I also fixed another unit test that would pass if deserializing an invalid payload panicked.

**Comment by stepancheg** [comment]
Thanks!

**Comment by fulmicoton** [comment]
you're welcome

**Pull request merged**
