### PR TITLE
Upgrade from outdated tempfile crate

### PR DESCRIPTION
**Pull request by glebpom**

### CODE REVIEW

**Comment by stepancheg** [comment]
Note travis-ci failures.

**Comment by stepancheg** [comment]
OK, why do we need to upgrade `tempfile` to `tempdir`? I've just opened [tempdir crate homepage](https://github.com/Stebalien/tempfile) and haven't found anything wrong: the project seems to be alive and there is no deprecation or suggestions to migrate to `tempfile`.

**Comment by glebpom** [comment]
hey, sorry, that's a mistake. Just got messed with different variants of temp files management crates. The goal was to stop using outdated `rand`  crate (v0.4), which was a dependency of `tempdir` (instead of `tempfile`, heh), which was used by `protoc-rust` version `2.2.2`. In fact, it has already been fixed in a `master` version of `protoc-rust`. Closing the PR.

**Comment by stepancheg** [comment]
@glebpom I'm not sure what's fixed in master, but if some commit needs to be ported to stable branches, please open an issue or PR, because master won't be released any time soon. Thanks!

**Comment by glebpom** [comment]
Please, take a look at https://github.com/stepancheg/rust-protobuf/pull/374

**Pull request closed without merging**
