### PR TITLE
Improve dynamic message support

### PR DESCRIPTION
**Pull request by benesch**
Implement merge_message and friends for dynamic messages.

This is an extraction of @Dixeran's work from #549 that does not involve
making changes to FileDescriptor generation.

### CODE REVIEW

**Comment by benesch** [comment]
Ping @stepancheg!

**Comment by stepancheg** [comment]
Ok, I cherry-picked parts of this PR, some as is, some with changes.

It is committed to master now.

Next time, I'd appreciate if:
* it is smaller PRs. It could be easily split into parsing/serializing for example, and possibly into smaller parts.
* tests help. I commited code, but I'm not sure it works.

That said, thank you very much.

Now I need to write tests for this and implement missing parts like map field.

**Comment by stepancheg** [comment]
OK, seems like it works. This is basic serialization/deserialization test: 92b1431f74c1d2c722b1d69ad2ef81633d11fe08.

Closing this PR, although more work is needed for dynamic messages.

**Comment by stepancheg** [comment]
Oh, one note.

In your PR you reset all fields before merge. I didn't get why it is needed, and it seems to be incorrect. So I did not pick it.

There was a statement I recall from protobuf documentation is that we can concatenate two messages and get correct message with merged fields. With fields reset on merge, this does not hold.

**Pull request closed without merging**
