### PR TITLE
Fix inconsistencies in protobuf-codegen-pure, part 1

### PR DESCRIPTION
**Pull request by benesch**
Split out from #484.

The big piece of work is the testing infrastructure for verifying that protoc-rust and protobuf-codegen-pure have identical output.

Then, there are two commits that demonstrate the process of fixing inconsistencies. When fixing an inconsistency results in two test files producing identical output, those files can be removed from the `except_fail` list in `test_diff`.

If this looks good, after it merges I'll start opening PRs one-by-one for the more complicated bits of #484.

### CODE REVIEW

**Comment by benesch** [comment]
Ok, finally got the tests here passing! There was a latent bug in how module names were constructed on Windows for which I've included a fix.

**Comment by stepancheg** [comment]
Looks good.

Can I request two changes in this PR please?

* move test into a separate, third crate, like `protobuf-codegen-identical-test' or something. It is slightly inconvenient that we need to build `protobuf-test` to test `protobuf-codegen-pure-test`
* mark inconsistent files inside the files instead of a list of files in the test

Something like, in a file `test.proto`:

```
// @skip-codegen-identical-test

message A { ... }
```

This way it will be much easier to maintain these files)

(although, third-party definitions — Google protobuf — should be filtered in the test description as in this PR)

And another issue: this test reads generated files from test crate sources. It would probably be better to invoke codegen directly from consistency test instead of depending on test crates. Although that would be a quite large change, we can do that later.

**Comment by benesch** [comment]
> Can I request two changes in this PR please?
> 
> * move test into a separate, third crate, like `protobuf-codegen-identical-test` or something. It is slightly inconvenient that we need to build `protobuf-test`to test`protobuf-codegen-pure-test`

Done.

> * mark inconsistent files inside the files instead of a list of files in the test
> 
> Something like, in a file `test.proto`:
> 
> ```
> // @skip-codegen-identical-test
> 
> message A { ... }
> ```

Done. This turned out to be really hard, though, with the previous design of the test, as it is in general impossible to find the source `.proto` file based on the path of the generated `.rs` file. E.g., `foo.proto` generates `foo.rs`, but `struct.proto` generates `struct_pb.rs` and `bad~name.proto` generates `bad_name.rs`.

So I reworked the design of the test entirely, and as a side-effect addressed this issue as well:

> And another issue: this test reads generated files from test crate sources. It would probably be better to invoke codegen directly from consistency test instead of depending on test crates. Although that would be a quite large change, we can do that later.

The new design doesn't bother running codegen, as codegen is a pure function from a `FileDescriptorSet` to generated Rust code. Instead we just check check that `protoc-codegen-pure` generates the same `FileDescriptorSet` as the `protoc` binary would. 

Note that the new `protobuf-codegen-identical-test` crate still winds up depending on the `protobuf-test` crate, as the `.proto` files in test/common/v3 are generated by build.rs, and it didn't seem right to duplicate that logic.

**Comment by stepancheg** [comment]
> The new design doesn't bother running codegen, as codegen is a pure function from a FileDescriptorSet

I took your stack and modified it back to what you did before: now the test compares generated `.rs` files, not descriptors.

There are many legitimate reasons why descriptors may not be equal but semantically equivalent
* omitting the syntax field which you fixed in one of the commits is one of many possible reasons
* potential descriptor extensions of descriptors with new fields in `protoc` command is another possibility

> Note that the new protobuf-codegen-identical-test crate still winds up depending on the protobuf-test crate

I removed that dependency (because `protobuf-test` crate is slow to compile). `protobuf-codegen-identical-test` crate should generate it's own copy of `v3` files using code from `protobuf-test-common` crate. I commented out `common/v3` tests as TODO.

Also, I changed diff printer to invoke external `diff` command instead of using `difference` crate since `difference` is too slow when comparing generated `.rs` files.

I preserved your name in the commit author field since you did the largest part of the job. Thank you very much!

**Comment by stepancheg** [comment]
> I commented out common/v3 tests as TODO.

Fixed in 9b17bb6de41ac1a6eaa991b7395974dc8b57b929

**Comment by benesch** [comment]
Awesome, thanks very much @stepancheg!

**Pull request closed without merging**
