### PR TITLE
Add Cargo.lock file

### PR DESCRIPTION
**Pull request by lucperkins**
I recently wanted to add a package for `protoc-gen-rust` to Nixpkgs but was stymied because the `buildRustPackage` derivation requires a lock file. I considered using a fork for the package instead, but I feel it'd be more optimal to make the change directly here.

### CODE REVIEW

**Comment by stepancheg** [comment]
Rust recommendation is not to commit `Cargo.lock`:

> If you’re building a non-end product, such as a rust library that other rust [packages](https://doc.rust-lang.org/cargo/appendix/glossary.html#package) will depend on, put Cargo.lock in your .gitignore.

https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html

**Comment by lucperkins** [comment]
In this case, though, there are also executables being shipped, not just libraries. So I feel that that particular recommendation doesn't apply. If you'd like those executables to be included in reproducible builds, I do think that the lockfile is necessary.

**Comment by stepancheg** [comment]
> In this case, though, there are also executables being shipped, not just libraries. 

But `Cargo.lock` applies to all of them, including libraries.

**Comment by lucperkins** [comment]
Suit yourself. I'll use a fork and `protoc-gen-rust` will be prevented from inclusion in Nixpkgs.

**Pull request closed without merging**
