### PR TITLE
*: add lite-runtime customization options

### PR DESCRIPTION
**Pull request by BusyJay**
Some times, it may not be suitable to enable lite-runtime for all languages.
For java, it even warns about generating broken code. However
rust-protobuf can only enable lite runtime through the default file
option, which makes it difficult to work with different languages.

This pull request provides an additional way to enable the flag, so lite
runtime can be enabled for rust while disabled for all other languages.

### CODE REVIEW

**Comment by stepancheg** [comment]
I though I have removed lite_runtime options long time ago.

Does it still do something useful? Does it reduce code size significantly?

**Comment by BusyJay** [comment]
Yes, it removes more than 10000+ lines of code in our project.

**Comment by stepancheg** [comment]
Is the line count important?

I think the generated machine code size is the largest issue now (and avoiding generation of descriptors reduces generated code size just a little, please correct me if I'm wrong).

This is the issue: https://github.com/stepancheg/rust-protobuf/issues/339

Unfortunately, I don't know a good solution to this problem.

**Comment by stepancheg** [comment]
OK, since `LITE_RUNTIME` is already in stable, there is no harm adding this option.

So I merged this PR (as 1a0c2f433e40fa85df61314afdc2bd78985ccd1d).

However, no promises that lite runtime option will exist in the next big major version.

Thanks!

**Comment by stepancheg** [comment]
Reopening the PR since this need to be merged to stable branch.

**Comment by stepancheg** [comment]
Merged to 2.5 branch.

**Pull request closed without merging**
