### PR TITLE
Add an option to box oneof fields of kind message

### PR DESCRIPTION
**Pull request by hurryabit**
Currently, `protoc-rust` cannot handle _mutually_ recursive messages with oneofs, even with `singular_field_option_box` enabled. For instance, the example
```protobuf
message A {
    oneof a {
        int32 i = 1;
        B b = 2;
    }
}

message B {
    oneof b {
        int32 i = 1;
        A a = 2;
    }
}
```
produces Rust code whose compilation fails with
```
error[E0072]: recursive type `common::v2::test_oneof_recursive_pb::A` has infinite size
   --> protobuf-test/src/common/v2/test_oneof_recursive_pb.rs:273:1
    |
273 | pub struct A {
    | ^^^^^^^^^^^^ recursive type has infinite size
274 |     // message oneof groups
275 |     pub a: ::std::option::Option<a::A>,
    |     ---------------------------------- recursive without indirection
    |
    = help: insert indirection (e.g., a `Box`, `Rc`, or `&`) at some point to make `common::v2::test_oneof_recursive_pb::A` representable
```
For recursive messages that do not go through other messages in the recursive cycle, this problem has been fixed by an _ad-hoc_ check to detect these messages and adding `Box`es where necessary:
https://github.com/stepancheg/rust-protobuf/blob/0674fbba3a091667f9b345f5a785e2377adab8c4/protobuf-codegen/src/oneof.rs#L35
Unfortunately, this recursion detection does not easily extend to mutually recursive messages.

This PR proposes to solve the problem by allowing the user to specify when oneof fields should be boxed. Therefore, we introduce an option `oneof_field_box` that works like `singular_field_option_box` but on oneof fields of kind message. Fortunately, the infrastructure for doing the boxing/unboxing has already been implemented for the existing _ad-hoc_ recursion check. Thus, we only need to pass the option into the right place and add a few tests.

---
This change is [Reviewable](https://reviewable.io/reviews/stepancheg/rust-protobuf/420)

### CODE REVIEW

**Comment by stepancheg** [comment]
Having an option is OK, but I think this case should work automatically without additional options specified.

>  Unfortunately, this recursion detection does not easily extend to mutually recursive messages.

I think it's doable.

I need to try to implement it, and if you want to try it yourself, go ahead.

**Comment by stepancheg** [comment]
I have implemented recursion detection in 5d706565de43618ce6f0094d75b904544f0a7644.

Is `oneof_field_box` still necessary?

Keeping this PR open because this commit needs to be backported to the stable branch.

Thank you for the bugreport/PR!

**Comment by stepancheg** [comment]
Ported to 2.7 branch c4ca2e9ca87b56a67232d526b1ffc234752c537e.

2.7 will be released in ~1-2 weeks. Please let me know if this is critical and need to be released earlier.

**Comment by stepancheg** [comment]
I'd apprecate code review BTW, because there's a chance I overlooked something.

**Comment by hurryabit** [comment]
@stepancheg I had a look at your fix. The code looks reasonable and simpler than I expected. Thanks a lot for fixing this so quickly!

I'm currently using a pinned version from the master branch. A quick release of 2.7 is hence not critical for me.

**Pull request closed without merging**
